name: ETL Pipeline

on:
  push:
    branches:
      - main

jobs:

  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract data from MySQL
        run: python extract.py

  transform-job:
    runs-on: ubuntu-latest
    needs: extract-job  # ensures extract runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transform data
        run: python transform.py

  load-job:
    runs-on: ubuntu-latest
    needs: transform-job  # ensures transform runs before load
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load data into MySQL
        run: python load.py
